# Generated by Django 4.2.2 on 2023-06-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uni',
            fields=[
                ('UniId', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=150)),
                ('universidad', models.CharField(max_length=150)),
                ('clave', models.BigIntegerField()),
                ('camiones', models.IntegerField()),
                ('vans', models.IntegerField()),
                ('carros', models.IntegerField()),
                ('hotel', models.CharField(max_length=150)),
                ('requerimientos', models.CharField(max_length=150)),
                ('guias', models.IntegerField()),
            ],
        ),
    ]
