# Generated by Django 4.2.2 on 2023-06-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uni',
            name='clave',
            field=models.CharField(max_length=150),
        ),
    ]
