# Generated by Django 4.2.2 on 2023-06-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_uni_clave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parti',
            fields=[
                ('PartiId', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.IntegerField()),
                ('universidad', models.CharField(max_length=150)),
                ('nombre', models.CharField(max_length=150)),
                ('grado', models.CharField(max_length=10)),
                ('carrera', models.CharField(max_length=150)),
                ('curp', models.CharField(max_length=150)),
                ('disciplina', models.IntegerField()),
                ('rama', models.IntegerField()),
                ('FechaIngre', models.DateField()),
                ('cicloescolar', models.CharField(max_length=150)),
                ('sexo', models.CharField(max_length=150)),
                ('nss', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Uni',
        ),
    ]
