# Generated by Django 4.2.2 on 2023-06-13 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_parti_delete_uni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parti',
            name='disciplina',
            field=models.CharField(choices=[('', '-- Seleccione una disciplina --'), (1, 'Ajedrez'), (2, 'Atletismo '), (3, 'Baloncesto'), (4, 'Canto'), (5, 'Declamacion'), (6, 'Oratoria'), (7, 'Voleibol'), (8, 'Taekwondo'), (9, 'Mural en gis'), (10, 'Softbol'), (11, 'Rondalla'), (12, 'Fútbol 7'), (13, 'Futbol asociacion')], max_length=150),
        ),
        migrations.AlterField(
            model_name='parti',
            name='rama',
            field=models.CharField(choices=[('', '-- Seleccione una Rama --'), (1, 'Varonil'), (2, 'Femenil')], max_length=150),
        ),
    ]
