# Generated by Django 4.2.2 on 2023-06-15 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_parti_disciplina_alter_parti_rama'),
    ]

    operations = [
        migrations.AddField(
            model_name='parti',
            name='archivos',
            field=models.FileField(default=1, upload_to='archivos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parti',
            name='fotos',
            field=models.ImageField(default=1, upload_to='imagenes'),
            preserve_default=False,
        ),
    ]
