# Generated by Django 4.2.2 on 2023-06-15 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_parti_archivos_parti_fotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parti',
            name='fotos',
            field=models.ImageField(upload_to='imagenes/'),
        ),
    ]
