# Generated by Django 4.2.2 on 2023-06-17 23:25

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_parti_archivos_remove_parti_fotos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entre',
            fields=[
                ('EntreId', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('ape_patern', models.CharField(max_length=150)),
                ('ape_mater', models.CharField(max_length=150)),
                ('telefono_ofic', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('celular', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('disciplina', models.IntegerField(choices=[('', '-- Seleccione una disciplina --'), (1, 'Ajedrez'), (2, 'Atletismo '), (3, 'Baloncesto'), (4, 'Canto'), (5, 'Declamacion'), (6, 'Oratoria'), (7, 'Voleibol'), (8, 'Taekwondo'), (9, 'Mural en gis'), (10, 'Softbol'), (11, 'Rondalla'), (12, 'Fútbol 7'), (13, 'Futbol asociacion')])),
                ('rama', models.IntegerField(choices=[('', '-- Seleccione una Rama --'), (1, 'Varonil'), (2, 'Femenil')])),
                ('fotografia', models.ImageField(upload_to='imagenes/')),
            ],
        ),
    ]
