# Generated by Django 4.2.2 on 2023-06-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_entre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entre',
            name='disciplina',
            field=models.CharField(choices=[('', '-- Seleccione una disciplina --'), ('Ajedrez', 'Ajedrez'), ('Atletismo', 'Atletismo'), ('Baloncesto', 'Baloncesto'), ('Canto', 'Canto'), ('Declamación', 'Declamación'), ('Oratoria', 'Oratoria'), ('Voleibol', 'Voleibol'), ('Taekwondo', 'Taekwondo'), ('Mural en gis', 'Mural en gis'), ('Softbol', 'Softbol'), ('Rondalla', 'Rondalla'), ('Fútbol 7', 'Fútbol 7'), ('Fútbol asociación', 'Fútbol asociación')], max_length=150),
        ),
        migrations.AlterField(
            model_name='entre',
            name='rama',
            field=models.CharField(choices=[('', '-- Seleccione una Rama --'), ('Varonil', 'Varonil'), ('Femenil', 'Femenil')], max_length=150),
        ),
        migrations.AlterField(
            model_name='parti',
            name='disciplina',
            field=models.CharField(choices=[('', '-- Seleccione una disciplina --'), ('Ajedrez', 'Ajedrez'), ('Atletismo', 'Atletismo'), ('Baloncesto', 'Baloncesto'), ('Canto', 'Canto'), ('Declamación', 'Declamación'), ('Oratoria', 'Oratoria'), ('Voleibol', 'Voleibol'), ('Taekwondo', 'Taekwondo'), ('Mural en gis', 'Mural en gis'), ('Softbol', 'Softbol'), ('Rondalla', 'Rondalla'), ('Fútbol 7', 'Fútbol 7'), ('Fútbol asociación', 'Fútbol asociación')], max_length=150),
        ),
        migrations.AlterField(
            model_name='parti',
            name='rama',
            field=models.CharField(choices=[('', '-- Seleccione una Rama --'), ('Varonil', 'Varonil'), ('Femenil', 'Femenil')], max_length=150),
        ),
    ]
