# Generated by Django 4.2.2 on 2023-06-20 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_uni'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Uni',
        ),
    ]
