# Generated by Django 4.2.2 on 2023-07-06 01:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_uni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entre',
            name='telefono_ofic',
        ),
        migrations.AlterField(
            model_name='entre',
            name='celular',
            field=models.CharField(default=1, max_length=15, validators=[django.core.validators.RegexValidator(message='El número de teléfono móvil debe tener entre 9 y 15 dígitos.', regex='^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entre',
            name='Telefono_ofic',
            field=models.CharField(default=1, max_length=10, validators=[django.core.validators.RegexValidator(message='El número de casa debe tener entre 1 y 10 dígitos.', regex='^\\d{1,10}$')]),
            preserve_default=False,
        ),
    ]
