# Generated by Django 4.2.2 on 2023-07-11 16:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0016_rename_telefono_ofic_entre_telefono_ofic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entre',
            name='celular',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El número de teléfono móvil debe tener entre 9 y 10 dígitos.', regex='^\\+?1?\\d{9,10}$')]),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('U', 'Usuario'), ('A', 'Administador'), ('S', 'Super usuario')], default='U', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
