# Generated by Django 4.2.2 on 2023-07-19 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_entre_user_uni_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entre',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
        ),
    ]
