# Generated by Django 4.2.2 on 2023-07-20 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_entre_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entre',
            name='user',
        ),
        migrations.RemoveField(
            model_name='uni',
            name='user',
        ),
    ]
