# Generated by Django 4.2.2 on 2023-07-20 03:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0024_cordi_suple'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordi',
            fields=[
                ('corId', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=150)),
                ('Ape_Pate', models.CharField(max_length=150)),
                ('Ape_Mate', models.CharField(max_length=150)),
                ('telefono_ofic', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El número de casa debe tener entre 1 y 10 dígitos.', regex='^\\d{1,10}$')])),
                ('celular', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El número de teléfono móvil debe tener entre 9 y 10 dígitos.', regex='^\\+?1?\\d{9,10}$')])),
                ('email', models.EmailField(max_length=254)),
                ('fotografia', models.ImageField(upload_to='imagenes/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Cordi',
        ),
    ]
