# Generated by Django 4.2.2 on 2023-07-20 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_coordi_fotografia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordi',
            name='user',
        ),
        migrations.RemoveField(
            model_name='entre',
            name='user',
        ),
    ]
