# Generated by Django 4.2.2 on 2023-07-20 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_coordi_user_remove_entre_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coordi',
        ),
        migrations.DeleteModel(
            name='Suple',
        ),
    ]
