# Generated by Django 4.2.2 on 2023-07-20 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_coordi_suple'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parti',
            name='user',
        ),
    ]
