# Generated by Django 4.2.2 on 2023-07-31 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_remove_parti_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='universidad',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
