# Generated by Django 4.2.2 on 2023-08-01 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_asis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medi',
            fields=[
                ('MedId', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('ape_patern', models.CharField(max_length=150)),
                ('ape_mater', models.CharField(max_length=150)),
                ('cedula', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El número de teléfono móvil debe tener entre 9 y 10 dígitos.', regex='^\\+?1?\\d{9,10}$')])),
                ('fotografia', models.ImageField(upload_to='medicos/')),
            ],
        ),
    ]
