# Generated by Django 4.2.2 on 2023-08-03 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_staff_alter_parti_curp_alter_parti_nss'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
