# Generated by Django 4.2.2 on 2023-08-03 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_delete_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('StId', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('ape_patern', models.CharField(max_length=150)),
                ('ape_mater', models.CharField(max_length=150)),
                ('celular', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El número de teléfono móvil debe tener entre 9 y 10 dígitos.', regex='^\\+?1?\\d{9,10}$')])),
                ('fotografia', models.ImageField(upload_to='staff/')),
            ],
        ),
    ]
