# Generated by Django 4.2.2 on 2023-08-04 04:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suple',
        ),
        migrations.AddField(
            model_name='coordi',
            name='cel_suple',
            field=models.CharField(default=1, max_length=10, validators=[django.core.validators.RegexValidator(message='El número de teléfono móvil debe tener entre 9 y 10 dígitos.', regex='^\\+?1?\\d{9,10}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coordi',
            name='nom_suple',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entre',
            name='rama',
            field=models.CharField(blank=True, choices=[('', '-- Seleccione una Rama --'), ('Varonil', 'Varonil'), ('Femenil', 'Femenil'), ('Mixto', 'Mixto')], default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='parti',
            name='rama',
            field=models.CharField(blank=True, choices=[('', '-- Seleccione una Rama --'), ('Varonil', 'Varonil'), ('Femenil', 'Femenil'), ('Mixto', 'Mixto')], default='', max_length=150, null=True),
        ),
    ]
