# Generated by Django 4.2.2 on 2023-08-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_delete_suple_coordi_cel_suple_coordi_nom_suple_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parti',
            name='sexo',
            field=models.CharField(blank=True, choices=[('', '--Seleccione el sexo--'), ('Hombre', 'Homre'), ('Mujer', 'Mujer')], default='', max_length=150, null=True),
        ),
    ]
