# Generated by Django 4.2.2 on 2023-08-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_parti_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='parti',
            name='ape_mater',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parti',
            name='ape_patern',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
