# Generated by Django 4.2.2 on 2023-08-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_parti_ape_mater_parti_ape_patern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parti',
            name='grado',
            field=models.CharField(blank=True, choices=[('', '--Seleccione el Grado--'), ('1', ''), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='', max_length=150, null=True),
        ),
    ]
